# node as builder
FROM node:lts AS builder
WORKDIR /app
COPY webui webui

WORKDIR /app/webui
RUN npm run build-prod

# final image
FROM nginx:stable
COPY --from=builder /app/webui/dist /usr/share/nginx/html