version: '3'

services:
  
  backend:
    image: backend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./shared:/shared
  
  frontend: 
    image: frontend:latest
    ports:
      - "8080:80"